name: ci

on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
        timeout-minutes: 3
      - run: bun run lint:ci
        timeout-minutes: 3
      - run: bun x tsc --noEmit
        timeout-minutes: 3
      - run: bun test test
        timeout-minutes: 5
      - run: bun run build
        timeout-minutes: 3
